#!/usr/bin/env bash

IFS=$'\n'      # Change IFS to new line
subscriptions=($(az account list --query "[].name" -o tsv | sort))

index=0
for subscription in ${subscriptions[*]};
do
   index=$(( index+1 ));
   echo "$index) $subscription";
done

printf "Choice a number: "
read -r choice

echo "Changing to subscription ${subscriptions[choice-1]}..."
az account set -s "${subscriptions[choice-1]}"
echo "Done"