#!/usr/bin/env bash

IFS=$'\n'      # Change IFS to new line
namespaces=($(kubectl get namespaces -o name | cut -d'/' -f2 | sort))

index=0
for namespace in ${namespaces[*]};
do
   index=$(( index+1 ));
   echo "$index) $namespace";
done

printf "Choice a number: "
read -r choice

echo "Changing to namespace ${namespaces[choice-1]}..."
kubectl config set-context --current --namespace ${namespaces[choice-1]}
echo "Done"