---

- hosts: all
  tasks:
    - name: verify internet connectivity
      wait_for:
        host: www.google.com
        port: 443
        timeout: 3

    - name: install packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - epel-release
        - python36
        - python
        - python-pip

    - name: install pip for python 3.6
      command: "python36 -m ensurepip"

    - name: add aliases for python3
      lineinfile:
        path: /home/vagrant/.bashrc
        line: "{{ item }}"
      loop:
        - alias pip3='python36 -m pip'
        - alias python3='python36'

    - name: install pipenv
      command: 'python36 -m pip install pipenv'