---

- name: Basic package install and checks
  hosts: all
  tasks:
    - name: verify internet connectivity
      wait_for:
        host: www.google.com
        port: 443
        timeout: 3

    - name: install packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - epel-release
        - python36
        - python
        - python-pip
        - unzip
        - docker
        - nodejs
        - npm
        - https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
        - dotnet-sdk-2.1

- name: Bring ssh configuration and keys from the host to the guest
  hosts: all
  tasks:
    - name: copy key files to the guest
      copy:
        remote_src: yes
        src: /ssh/{{ item }}
        dest: /home/vagrant/.ssh/{{ item }}
        mode: 0700
        owner: vagrant
        group: vagrant
      loop:
        - id_rsa
        - id_rsa.pub
        - config


- name: Configure python3 on CentOS
  hosts: all
  tasks:
    - name: install pip for python 3.6
      command: "python36 -m ensurepip"

    - name: add aliases for python3
      lineinfile:
        path: /home/vagrant/.bashrc
        line: "{{ item }}"
      loop:
        - alias pip3='python36 -m pip'
        - alias python3='python36'

    - name: install pipenv
      command: 'python36 -m pip install pipenv'

- name: Install Terraform
  hosts: all
  vars:
    terraform_temp_zip_path: /tmp/terraform.zip
  tasks:
    - name: fetch Terraform
      get_url:
        url: https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip
        dest: "{{ terraform_temp_zip_path }}"
    - name: Unzip terraform binary
      unarchive:
        src: "{{ terraform_temp_zip_path }}"
        dest: /usr/local/bin
        remote_src: yes

- name: Configure docker
  hosts: all
  tasks:
    - name: add docker group
      group:
        name: docker
    - name: Add vagrant to docker group # this allow calling docker wihout sudo
      user:
        name: vagrant
        groups: docker
        append: yes
    - name: Get docker daemon.json file
      set_fact:
        docker_config: "{{ lookup('file', '/etc/docker/daemon.json')|from_json }}"
    - name: Set new bip to docker config
      set_fact:
        docker_config: "{{ docker_config|combine({'bip': '192.168.1.5/24'}) }}"
    - name: Dump new configuration
      copy:
        content: "{{ docker_config | to_nice_json }}"
        dest: /etc/docker/daemon.json
    - name: Enable docker on systemd
      service:
        name: docker
        state: restarted
        enabled: true

- name: Install Tsuru client for 1.4
  hosts: all
  vars:
    tsuru_temp_zip_path: /tmp/tsuruclient.zip
  tasks:
    - name: fetch Tsuru client
      get_url:
        url: https://github.com/tsuru/tsuru-client/releases/download/1.4.0/tsuru_1.4.0_linux_amd64.tar.gz
        dest: "{{ tsuru_temp_zip_path }}"
    - name: Unzip tsuru client binary
      unarchive:
        src: "{{ tsuru_temp_zip_path }}"
        dest: /usr/local/bin
        remote_src: yes

